# Generated by Django 4.2.1 on 2023-06-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField(default='')),
                ('type', models.CharField(choices=[('ct', 'cat'), ('dg', 'dog'), ('hs', 'hamster'), ('gp', 'guinea pig'), ('all', 'all kind')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
