# Generated by Django 4.2.1 on 2023-06-15 14:38

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='hf', null=True, upload_to=shop.models.uploads_url, width_field='wf'),
        ),
        migrations.AddField(
            model_name='product',
            name='wf',
            field=models.IntegerField(default=0),
        ),
    ]
