# Generated by Django 4.2.1 on 2023-06-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_hf_product_image_product_wf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(choices=[('fd', 'feed'), ('ac', 'accessories'), ('ps', 'peels')], default='none', max_length=30),
        ),
    ]
