# Generated by Django 4.2.1 on 2023-06-10 20:23

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=blog.models.uploads_url, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='blog',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
