# Generated by Django 4.2.1 on 2023-06-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_height_field_blog_image_blog_width_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='all_description',
            field=models.TextField(default=''),
        ),
    ]
